# global settings
title: "Schachverein Dresden-Striesen e.V."
description: "Offizielle Website des Schachvereins Dresden-Striesen e.V. - Informationen zu Vereinsturnieren, Mannschaftskämpfen, Jugendarbeit und mehr."
# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/Vereins-Wiki"
repository: "Schachverein-Dresden-Striesen/Vereins-Wiki"
# relative_permalinks: false
theme: jekyll-theme-architect
email: info@sv-dresden-striesen.de
include:
  - files
  - pages
  - images

plugins:
  - jekyll-relative-links