# global settings
title: "Vereins-Wiki SV Dresden-Striesen"
description: "Noch im Aufbau: eine strukturierte Übersicht über alle Vereinsinformationen."
baseurl: "" # the subpath of your site
relative_permalinks: false
theme: jekyll-theme-architect
email: info@sv-dresden-striesen.de
include:
  - files
  - pages
  - images