name: Jekyll CI

on:
  pull_request:
    paths:
      - '!README.md'
      - '!THEME_MIGRATION.md'
      - '**' # Run on all files except README.md and THEME_MIGRATION.md

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Jekyll dependencies
        run: bundle install

      - name: Test Jekyll build
        run: bundle exec jekyll build --verbose
      
      - name: Upload Jekyll build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: jekyll-site
          path: _site
