name: Jekyll site CI

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ "website" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Jekyll dependencies
        run: bundle install

      - name: Test Jekyll build
        run: bundle exec jekyll build --verbose
