name: Jekyll CI

on:
  pull_request:
    paths:
      - '!README.md'
      - '!THEME_MIGRATION.md'
      - '**' # Run on all files except README.md and THEME_MIGRATION.md

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Jekyll dependencies
        run: bundle install

      - name: Test Jekyll build
        run: bundle exec jekyll build --verbose
      
      - name: Upload Jekyll html build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-jekyll-site-pr${{ github.event.pull_request.number }}-run${{ github.run_number }}
          path: |
            _site/assets/
            _site/files/favicon/
            _site/**/*.html
            _site/**/*.svg
            _site/**/*.xml
